# Generated by Django 5.1.3 on 2024-11-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='current_owner',
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset_id',
            field=models.CharField(default='DEFAULT_ASSET_ID', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='procured_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
