# Generated by Django 5.1.3 on 2024-11-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipment_category_equipment_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Shared', 'Shared'), ('Reserved', 'Reserved')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Repair', 'Under Repair')], default='Active', max_length=15),
        ),
    ]
