# Generated by Django 5.1.3 on 2024-11-22 22:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_equipment_added_by_alter_equipment_asset_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_logs', to='inventory.equipment')),
            ],
        ),
    ]
