# Generated by Django 5.1.3 on 2024-11-22 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_ownershiplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershiplog',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='ownershiplog',
            name='start_date',
            field=models.DateField(),
        ),
    ]
